/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPromocoesRouteImport } from './routes/admin/promocoes'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminNotasFiscaisRouteImport } from './routes/admin/notas-fiscais'
import { Route as AdminFornecedoresRouteImport } from './routes/admin/fornecedores'
import { Route as AdminFluxoDeCaixaRouteImport } from './routes/admin/fluxo-de-caixa'
import { Route as AdminEstoqueRouteImport } from './routes/admin/estoque'
import { Route as AdminDevolucoesRouteImport } from './routes/admin/devolucoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminComprasRouteImport } from './routes/admin/compras'
import { Route as AdminColecoesRouteImport } from './routes/admin/colecoes'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminUsuariosRouteRouteImport } from './routes/admin/usuarios/route'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin/usuarios/index'
import { Route as AdminUsuariosNovoRouteImport } from './routes/admin/usuarios/novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotasFiscaisRoute = AdminNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFornecedoresRoute = AdminFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFluxoDeCaixaRoute = AdminFluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDevolucoesRoute = AdminDevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComprasRoute = AdminComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminColecoesRoute = AdminColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRouteRoute = AdminUsuariosRouteRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsuariosRouteRoute,
} as any)
const AdminUsuariosNovoRoute = AdminUsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminUsuariosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/usuarios': typeof AdminUsuariosRouteRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/devolucoes': typeof AdminDevolucoesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fluxo-de-caixa': typeof AdminFluxoDeCaixaRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/devolucoes': typeof AdminDevolucoesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fluxo-de-caixa': typeof AdminFluxoDeCaixaRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin/usuarios': typeof AdminUsuariosRouteRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/devolucoes': typeof AdminDevolucoesRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/fluxo-de-caixa': typeof AdminFluxoDeCaixaRoute
  '/admin/fornecedores': typeof AdminFornecedoresRoute
  '/admin/notas-fiscais': typeof AdminNotasFiscaisRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/promocoes': typeof AdminPromocoesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/admin/usuarios'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/devolucoes'
    | '/admin/estoque'
    | '/admin/fluxo-de-caixa'
    | '/admin/fornecedores'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/'
    | '/admin/usuarios/novo'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/devolucoes'
    | '/admin/estoque'
    | '/admin/fluxo-de-caixa'
    | '/admin/fornecedores'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin'
    | '/admin/usuarios/novo'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/admin/usuarios'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/compras'
    | '/admin/configuracoes'
    | '/admin/devolucoes'
    | '/admin/estoque'
    | '/admin/fluxo-de-caixa'
    | '/admin/fornecedores'
    | '/admin/notas-fiscais'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/'
    | '/admin/usuarios/novo'
    | '/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promocoes': {
      id: '/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notas-fiscais': {
      id: '/admin/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/admin/notas-fiscais'
      preLoaderRoute: typeof AdminNotasFiscaisRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fornecedores': {
      id: '/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AdminFornecedoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fluxo-de-caixa': {
      id: '/admin/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/admin/fluxo-de-caixa'
      preLoaderRoute: typeof AdminFluxoDeCaixaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/devolucoes': {
      id: '/admin/devolucoes'
      path: '/devolucoes'
      fullPath: '/admin/devolucoes'
      preLoaderRoute: typeof AdminDevolucoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/compras': {
      id: '/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AdminComprasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/colecoes': {
      id: '/admin/colecoes'
      path: '/colecoes'
      fullPath: '/admin/colecoes'
      preLoaderRoute: typeof AdminColecoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminUsuariosRouteRoute
    }
    '/admin/usuarios/novo': {
      id: '/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminUsuariosNovoRouteImport
      parentRoute: typeof AdminUsuariosRouteRoute
    }
  }
}

interface AdminUsuariosRouteRouteChildren {
  AdminUsuariosNovoRoute: typeof AdminUsuariosNovoRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminUsuariosRouteRouteChildren: AdminUsuariosRouteRouteChildren = {
  AdminUsuariosNovoRoute: AdminUsuariosNovoRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminUsuariosRouteRouteWithChildren =
  AdminUsuariosRouteRoute._addFileChildren(AdminUsuariosRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminUsuariosRouteRoute: typeof AdminUsuariosRouteRouteWithChildren
  AdminClientesRoute: typeof AdminClientesRoute
  AdminColecoesRoute: typeof AdminColecoesRoute
  AdminComprasRoute: typeof AdminComprasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDevolucoesRoute: typeof AdminDevolucoesRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminFluxoDeCaixaRoute: typeof AdminFluxoDeCaixaRoute
  AdminFornecedoresRoute: typeof AdminFornecedoresRoute
  AdminNotasFiscaisRoute: typeof AdminNotasFiscaisRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsuariosRouteRoute: AdminUsuariosRouteRouteWithChildren,
  AdminClientesRoute: AdminClientesRoute,
  AdminColecoesRoute: AdminColecoesRoute,
  AdminComprasRoute: AdminComprasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDevolucoesRoute: AdminDevolucoesRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminFluxoDeCaixaRoute: AdminFluxoDeCaixaRoute,
  AdminFornecedoresRoute: AdminFornecedoresRoute,
  AdminNotasFiscaisRoute: AdminNotasFiscaisRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
